language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

cache: pip

install:
  - pip install tox-travis
  - make requirements

script: tox
